In [1]:
import cv2
import numpy as np

import time

In [1]:
import cv2
import numpy as np
import time
import os
# for root, dirs, files in os.walk("/home/chirag/Downloads/GMRPD1/depth_u8", topdown=False):
#     for n in dirs:
#         for z in range(1,5):
#             d=z*5
while True:
    os.chdir("/home/chirag/Documents/OpenCV_vinay_sir")
    name="/home/chirag/Downloads/GMRPD1/depth_u8/streetlamp/2.png"
    print(name)
    s=name.split("/")[-2]+'/'+name.split("/")[-1]
    image=cv2.imread(name)
    
    max_disp = 255
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    IMAGE_HEIGHT, IMAGE_WIDTH = image.shape
    image= image
    print(max_disp)
    

    # calculate v-disparity
    vhist_vis = np.zeros((IMAGE_HEIGHT, max_disp), np.float)
    for i in range(IMAGE_HEIGHT):
        vhist_vis[i, ...] = cv2.calcHist(images=[image[i, ...]], channels=[0], mask=None, histSize=[max_disp],
                                         ranges=[0, max_disp]).flatten() / float(IMAGE_HEIGHT)


    vhist_vis = np.array(vhist_vis * 255, np.uint8)
    vblack_mask = vhist_vis < 5
    vhist_vis = cv2.applyColorMap(vhist_vis, cv2.COLORMAP_JET)
    vhist_vis[vblack_mask] = 0

    # calculate u-disparity
    uhist_vis = np.zeros((max_disp, IMAGE_WIDTH), np.float)
    for i in range(IMAGE_WIDTH):
        uhist_vis[..., i] = cv2.calcHist(images=[image[..., i]], channels=[0], mask=None, histSize=[max_disp],
                                         ranges=[0, max_disp]).flatten() / float(IMAGE_WIDTH)

    uhist_vis = np.array(uhist_vis * 255, np.uint8)
    ublack_mask = uhist_vis < 5
    uhist_vis = cv2.applyColorMap(uhist_vis, cv2.COLORMAP_JET)
    uhist_vis[ublack_mask] = 0
    

    image = cv2.applyColorMap(image, cv2.COLORMAP_JET)
    os.makedirs(name.split("/")[-2], exist_ok = True) 
    os.chdir(name.split("/")[-2])
    cv2.imshow('disparity_image_'+name.split("/")[-1], image)
    cv2.imshow('v_disparity_image_'+name.split("/")[-1], vhist_vis)
    cv2.imwrite('disparity_image_'+name.split("/")[-1], image)
    cv2.imwrite('v_disparity_image_'+name.split("/")[-1], vhist_vis)
    cv2.imwrite('u_disparity_image_'+name.split("/")[-1], uhist_vis)
    
    edged = cv2.Canny(vhist_vis, 30, 200)
    cv2.imshow('edge',edged)
    _, contours, _ = cv2.findContours(edged, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    cv2.drawContours(vhist_vis, contours, -1, (0, 255, 0), 3)
    os.chdir("/home/chirag/Documents/OpenCV_vinay_sir")
    cv2.imshow('v_disparity_image_2', vhist_vis)
    cv2.imwrite('u_disparity_ima',vhist_vis)
    
    os.chdir("/home/chirag/Documents/OpenCV_vinay_sir")
    
    if chr(cv2.waitKey(0)&255) == 'q':
        break
cv2.destroyAllWindows()

/home/chirag/Downloads/GMRPD1/depth_u8/streetlamp/2.png
255


error: OpenCV(3.4.2) /io/opencv/modules/imgproc/src/hough.cpp:472: error: (-215:Assertion failed) image.type() == (((0) & ((1 << 3) - 1)) + (((1)-1) << 3)) in function 'HoughLinesProbabilistic'


In [41]:
import os
for root, dirs, files in os.walk("/home/chirag/Downloads/GMRPD1/depth_u8", topdown=False):
    for name in dirs:
#         print os.path.join(root, name)
        print(name)
/home/chirag/Downloads/GMRPD1/depth_u8/pole/1.png

pole
scene9
scene7
scene6
scene8
scene1
scene4
scene10
scene2
streetlamp
scene3
others
scene5
firehydrant


In [40]:
print(os.walk("/home/chirag/Downloads/GMRPD1/depth_u8"))

<generator object walk at 0x7fd051381650>


In [ ]:
import cv2
import numpy as np
import time
import os
# for root, dirs, files in os.walk("/home/chirag/Downloads/GMRPD1/depth_u8", topdown=False):
#     for n in dirs:
#         for z in range(1,5):
#             d=z*5
while True:
    os.chdir("/home/chirag/Documents/OpenCV_vinay_sir")
    name="/home/chirag/Downloads/GMRPD1/depth_u8/firehydrant/1.png"
    print(name)
    s=name.split("/")[-2]+'/'+name.split("/")[-1]
    image=cv2.imread(name)
    image2=cv2.imread(name)
#     image = np.float32(image)
#     image2 = np.float32(image2)
    max_disp = 255
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    image2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)
    IMAGE_HEIGHT, IMAGE_WIDTH = image.shape
    image= image
    print(max_disp)
    
    u=  7000
    # calculate v-disparity
    vhist_vis = np.zeros((IMAGE_HEIGHT, max_disp), np.float)
    inverse =  np.zeros(image.shape, np.float)
    for i in range(IMAGE_HEIGHT):
        for j in range(IMAGE_WIDTH):
            if image[i][j] !=float(0):
#                 print(image2[i][j])
                image2[i][j] = float(u/image[i][j])
#                 print(image2[i][j])
    cv2.imshow('disp', image2)
    normalizedImg = np.zeros((800,800))
#     cv2.normalize(image2,  normalizedImg, 0, 255, cv2.NORM_MINMAX)
    image = image2
    for i in range(IMAGE_HEIGHT):
        vhist_vis[i, ...] = cv2.calcHist(images=[image[i, ...]], channels=[0], mask=None, histSize=[max_disp],
                                         ranges=[0, max_disp]).flatten() / float(IMAGE_HEIGHT)
    
    import math

    vhist_vis = np.array(vhist_vis * 255, np.uint8)
    vblack_mask = vhist_vis < 5
#     vhist_vis = cv2.applyColorMap(vhist_vis, cv2.COLORMAP_JET)
    vhist_vis[vblack_mask] = 0

    # calculate u-disparity
#     uhist_vis = np.zeros((max_disp, IMAGE_WIDTH), np.float)
#     for i in range(IMAGE_WIDTH):
#         uhist_vis[..., i] = cv2.calcHist(images=[image[..., i]], channels=[0], mask=None, histSize=[max_disp],
#                                          ranges=[0, max_disp]).flatten() / float(IMAGE_WIDTH)

#     uhist_vis = np.array(uhist_vis * 255, np.uint8)
#     ublack_mask = uhist_vis < 5
#     uhist_vis = cv2.applyColorMap(uhist_vis, cv2.COLORMAP_JET)
#     uhist_vis[ublack_mask] = 0
    
    lines = cv2.HoughLinesP(vhist_vis,1,1*np.pi/180,100,500,50)
    vhist_vis = cv2.cvtColor(vhist_vis, cv2.COLOR_GRAY2BGR)
    print(lines)
    filter_lines = []
    for line in lines:
        for x1,y1,x2,y2 in line:
            if x2 != x1:
                th = (y2-y1)/(x2-x1)
                thd = math.degrees(math.atan(th))
                print(thd)
                if abs(thd) > 75 and x1 > 20:
                    y2 = int(th*(255-x1) + y1)
                    cv2.line(vhist_vis,(x1,y1),(255,y2),(0,0,255),10)
                if (thd) > 50 and (thd) < 75:
                    y2 = int(th*(255-x1) + y1)
                    cv2.line(vhist_vis,(x1,y1),(255,y2),(0,255,0),2)
                    filter_lines.append(line)
    print(vhist_vis[10][10])
#     l = cv2.imread("/home/chirag/Downloads/GMRPD1/rgb/firehydrant/1.png")
    l = np.zeros((IMAGE_HEIGHT, IMAGE_WIDTH),np.float) 
    for i in range(IMAGE_HEIGHT):
#         a=np.unique(vhist_vis[i])
#         print(a)
#         l = np.zeros((IMAGE_HEIGHT, IMAGE_WIDTH))   
        for j in range(max_disp):
            if vhist_vis[i][j][1]==255:
                for k in range(IMAGE_WIDTH):
                    if image[i][k] > j-10 and image[i][k] < j+10:
                        l[i][k]=1
                        
        
       
#     for i in range(IMAGE_HEIGHT):
#         for k in range(IMAGE_WIDTH):
#             if l[i][k]!=1:
#                 l[i][k] = [0,0,0
        
                
    l = np.array(l* 255, np.uint8)
                        
            
            
            
#     image = cv2.applyColorMap(image, cv2.COLORMAP_JET)
#     os.makedirs(name.split("/")[-2], exist_ok = True) 
#     os.chdir(name.split("/")[-2])
#     cv2.imshow('disparity_image_'+name.split("/")[-1], image)
    cv2.imshow("RGB",l )
    cv2.imshow('v_disparity_image_'+str(u)+name.split("/")[-1], vhist_vis)
    cv2.imwrite('disparity_image_'+str(u)+name.split("/")[-1], image)
    cv2.imwrite('v_disparity_image_'+str(u)+name.split("/")[-1], vhist_vis)
    cv2.imwrite('RGB.png', l)
#     cv2.imwrite('u_disparity_image_'+name.split("/")[-1], uhist_vis)
    
#     edged = cv2.Canny(vhist_vis, 30, 200)
# #     cv2.imshow('edge',edged)
#     _, contours, _ = cv2.findContours(edged, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
#     cv2.drawContours(vhist_vis, contours, -1, (0, 255, 0), 3)
    os.chdir("/home/chirag/Documents/OpenCV_vinay_sir")
#     cv2.imshow('v_disparity_image_2', vhist_vis)

    os.chdir("/home/chirag/Documents/OpenCV_vinay_sir")
    
    if chr(cv2.waitKey(0)&255) == 'q':
        break
cv2.destroyAllWindows()

/home/chirag/Downloads/GMRPD1/depth_u8/firehydrant/1.png
255
[[[  0 719   0 319]]

 [[ 27 327  67 397]]

 [[ 27 329  90 439]]

 [[ 43 365  90 446]]

 [[ 43 362  88 437]]

 [[ 93 407  93 353]]

 [[ 39 361  73 418]]

 [[ 92 443  92 392]]

 [[ 98 294  98 240]]

 [[100 301 100 246]]]
60.25511870305778
60.199056314380776
59.8756820016388
59.03624346792648
59.18429424827082
[0 0 0]
/home/chirag/Downloads/GMRPD1/depth_u8/firehydrant/1.png
255
[[[  0 719   0 319]]

 [[ 27 327  67 397]]

 [[ 27 329  90 439]]

 [[ 43 365  90 446]]

 [[ 43 362  88 437]]

 [[ 93 407  93 353]]

 [[ 39 361  73 418]]

 [[ 92 443  92 392]]

 [[ 98 294  98 240]]

 [[100 301 100 246]]]
60.25511870305778
60.199056314380776
59.8756820016388
59.03624346792648
59.18429424827082
[0 0 0]
/home/chirag/Downloads/GMRPD1/depth_u8/firehydrant/1.png
255


In [3]:
print(filter_lines)

[array([[ 27, 322,  90, 427]], dtype=int32), array([[ 27, 327,  81, 443]], dtype=int32), array([[ 53, 367,  90, 429]], dtype=int32), array([[ 27, 326,  67, 412]], dtype=int32), array([[ 37, 342,  60, 394]], dtype=int32)]


In [49]:
import cv2
import numpy as np
import time
import os
import glob
os.makedirs("images", exist_ok = True)
os.makedirs("Labels",exist_ok=True)
path = "/home/chirag/Downloads/GMRPD3/"
q=0


def draw_log(image, m,c):
	# y = log(mx, 2.0) + c
	for i in range(1,image.shape[1]):
		y = image.shape[1] - math.log(float(i),1.5) 
		# y = image.shape[1] - y
		# print(y,i)
		cv2.circle(image, (int(y)-m, i+c), 5, (250,255,0), -1)

	cv2.circle(image, (int(100),100), 10, (250,255,0), -1)
	return image

def red_area(image, threshv, label):
    if len(image.shape) == 2:
        image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
# print(threshv.shape)

    for i in range(image.shape[0]-1):
    	for j in range(image.shape[1]-1):
    		# print(i,j,image[i][j][0])
    		if image[i][j][0] <250 and image[i][j][0] > 10:
    			if threshv[i][image[i][j][0]][1] < 100 and threshv[i][image[i][j][0]][2] > 200:
    				cv2.circle(label, (j,i), 5, (0,0,255), -1)
    return label

def green_area(image, m, c, label):
    if len(image.shape) == 2:
        image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
	
    for i in range(image.shape[0]-1):
        for j in range(image.shape[1]-1):
            # print(i,j,image[i][j][0])
            if (image[i][j][2] <250 and image[i][j][2] > 10):
                y = i
                x = (y-c)/m

                if abs(x-image[i][j][0]) < 5:
                    cv2.circle(label, (j,i), 5, (250,255,0), -1)
    return label

def get_disp(image):
	image = image.astype('float')
	new_im = np.zeros(image.shape, np.float32)

	for i in range(image.shape[0]-1):
		for j in range(image.shape[1]-1):
			if(image[i][j] > 0):
				# print(6000.0/image[i][j])
				new_im[i][j] = 6250.0/image[i][j]

	# cv2.normalize(new_im, new_im, 0, 255, cv2.NORM_MINMAX)
	new_im = new_im.astype('uint8')
	return new_im

def get_line(lines):
	avg_m = 0
	avg_c = 0
	for line in lines:
	    for x1,y1,x2,y2 in line:
	    	m = (y2-y1)/(x2-x1)
	    	c = y2 - m*(x2)
	    	avg_m = avg_m+m
	    	avg_c = avg_c+c

	avg_m = avg_m/len(lines)
	avg_c = avg_c/len(lines)

	return (avg_m, avg_c)
count =0
for root, dirs, files in os.walk(path+"depth_u8", topdown=False):
    for n in dirs:
        for root1, dirs1, files2 in os.walk(path+"depth_u8/"+ n, topdown=False):
            for files1 in files2:
                print(q)

                depth = path+"depth_u8/"+ n +"/"+ files1
                rgb = path+"rgb/"+ n + "/" + files1
                print(depth,rgb)
                image=cv2.imread(depth)


                max_disp = 255
                image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
                IMAGE_HEIGHT, IMAGE_WIDTH = image.shape

                print(max_disp)

            
                # calculate v-disparity
                vhist_vis = np.zeros((IMAGE_HEIGHT, max_disp), np.float)
     
                image = get_disp(image)
            #     cv2.normalize(image2,  normalizedImg, 0, 255, cv2.NORM_MINMAX)
                
                for i in range(IMAGE_HEIGHT):
                    vhist_vis[i, ...] = cv2.calcHist(images=[image[i, ...]], channels=[0], mask=None, histSize=[max_disp],
                                                     ranges=[0, max_disp]).flatten() / float(IMAGE_HEIGHT)

                import math

                vhist_vis = np.array(vhist_vis * 255, np.uint8)
                vblack_mask = vhist_vis < 5
            #     vhist_vis = cv2.applyColorMap(vhist_vis, cv2.COLORMAP_JET)
                vhist_vis[vblack_mask] = 0
                cv2.normalize(vhist_vis, vhist_vis, 0, 255, cv2.NORM_MINMAX)
                vhist_vis = cv2.blur(vhist_vis, (5,5))
                vbin, threshv = cv2.threshold(vhist_vis, 10, 255, cv2.THRESH_BINARY)
                kernel = np.ones((3,3), np.uint8)
                # threshv = cv2.dilate(threshv,threshv, iterations=1)
                kernel = np.ones((3,3), np.uint8)
                pixelpoints = np.transpose(np.nonzero(vhist_vis))
                
                lines = cv2.HoughLinesP(vhist_vis,1,1*np.pi/180,100,500,50)
                vhist_vis = cv2.cvtColor(vhist_vis, cv2.COLOR_GRAY2BGR)
#                 print(lines)
                filter_lines = []
                for line in lines:
                    for x1,y1,x2,y2 in line:
                        if x2 != x1:
                            th = (y2-y1)/(x2-x1)
                            thd = math.degrees(math.atan(th))
#                             print(thd)
                            if abs(thd) > 75 and x1 > 20:
                                y2 = int(th*(255-x1) + y1)
                                cv2.line(vhist_vis,(x1,y1),(255,y2),(0,0,255),10)
                            if (thd) > 50 and (thd) < 75:
                                y2 = int(th*(255-x1) + y1)
                                cv2.line(vhist_vis,(x1,y1),(255,y2),(0,255,0),2)
                                filter_lines.append(line)

            #     l = cv2.imread("/home/chirag/Downloads/GMRPD1/rgb/firehydrant/1.png")
                
                l = np.zeros((IMAGE_HEIGHT, IMAGE_WIDTH),np.float) 
                for i in range(IMAGE_HEIGHT):   
                    for j in range(max_disp):
                        if vhist_vis[i][j][1]==255 and vhist_vis[i][j][0]==0 and vhist_vis[i][j][2]==0:
                            for k in range(IMAGE_WIDTH):
                                if image[i][k] > j-10 and image[i][k] < j+10:
                                    l[i][k]=1
                                    
                a, cnts = np.unique(l, return_counts=True)
                if a[1]==1:
                    cnt = cnts[1]
                else:
                    cnt = cnts[0]
                print(cnt/(IMAGE_HEIGHT * IMAGE_WIDTH))
                if (cnt/(IMAGE_HEIGHT * IMAGE_WIDTH))>0.2:
                    l = np.array(l* 255, np.uint8)

                    cv2.imwrite("Labels/" + str(q)+'.png', l)
                    RGB = cv2.imread(rgb)
                    depth= cv2.imread(depth,cv2.IMREAD_UNCHANGED)
                    depth=depth.reshape((depth.shape[0], depth.shape[1], 1))
                    x = np.zeros((depth.shape[0], depth.shape[1], 4))
                    x[:,:,:3]= RGB
                    x[:,:,3:]= depth
#                     depth = cv2.cvtColor(depth, cv2.COLOR_BGR2GRAY)
                    
                    cv2.imwrite("images/" + str(q)+'.png', x)
#                     os.rename(rgb,"RGB/"+ str(q)+".png")
#                     os.rename(depth, "Depth/"+ str(q)+".png")
                    print(q)
                    q+=1
            
            


0
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/62.png /home/chirag/Downloads/GMRPD3/rgb/scene25/62.png
255
0.4606987847222222
0
1
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/2.png /home/chirag/Downloads/GMRPD3/rgb/scene25/2.png
255
0.49916124131944445
1
2
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/55.png /home/chirag/Downloads/GMRPD3/rgb/scene25/55.png
255
0.3411414930555556
2
3
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/41.png /home/chirag/Downloads/GMRPD3/rgb/scene25/41.png
255
0.4734288194444444
3
4
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/12.png /home/chirag/Downloads/GMRPD3/rgb/scene25/12.png
255
0.5000054253472223
4
5
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/29.png /home/chirag/Downloads/GMRPD3/rgb/scene25/29.png
255
0.49247395833333335
5
6
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/22.png /home/chirag/Downloads/GMRPD3/rgb/scene25/22.png
255
0.5140234375
6
7
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/109.png /home/chirag/Downloads/GMRPD3/rgb/scene

0.48072374131944445
62
63
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/108.png /home/chirag/Downloads/GMRPD3/rgb/scene25/108.png
255
0.4747135416666667
63
64
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/14.png /home/chirag/Downloads/GMRPD3/rgb/scene25/14.png
255
0.48469835069444445
64
65
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/86.png /home/chirag/Downloads/GMRPD3/rgb/scene25/86.png
255
0.29854600694444444
65
66
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/110.png /home/chirag/Downloads/GMRPD3/rgb/scene25/110.png
255
0.43512912326388886
66
67
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/18.png /home/chirag/Downloads/GMRPD3/rgb/scene25/18.png
255
0.45862955729166666
67
68
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/61.png /home/chirag/Downloads/GMRPD3/rgb/scene25/61.png
255
0.3589236111111111
68
69
/home/chirag/Downloads/GMRPD3/depth_u8/scene25/57.png /home/chirag/Downloads/GMRPD3/rgb/scene25/57.png
255
0.3104752604166667
69
70
/home/chirag/Downloads/GMRPD3/depth_u8/sce

0.45060438368055555
124
125
/home/chirag/Downloads/GMRPD3/depth_u8/scene27/33.png /home/chirag/Downloads/GMRPD3/rgb/scene27/33.png
255
0.42672417534722223
125
126
/home/chirag/Downloads/GMRPD3/depth_u8/scene27/47.png /home/chirag/Downloads/GMRPD3/rgb/scene27/47.png
255
0.4474381510416667
126
127
/home/chirag/Downloads/GMRPD3/depth_u8/scene27/10.png /home/chirag/Downloads/GMRPD3/rgb/scene27/10.png
255
0.4185709635416667
127
128
/home/chirag/Downloads/GMRPD3/depth_u8/scene27/15.png /home/chirag/Downloads/GMRPD3/rgb/scene27/15.png
255
0.43740125868055557
128
129
/home/chirag/Downloads/GMRPD3/depth_u8/scene27/28.png /home/chirag/Downloads/GMRPD3/rgb/scene27/28.png
255
0.4190549045138889
129
130
/home/chirag/Downloads/GMRPD3/depth_u8/scene27/17.png /home/chirag/Downloads/GMRPD3/rgb/scene27/17.png
255
0.421865234375
130
131
/home/chirag/Downloads/GMRPD3/depth_u8/scene27/32.png /home/chirag/Downloads/GMRPD3/rgb/scene27/32.png
255
0.43587565104166665
131
132
/home/chirag/Downloads/GMRPD3/depth

0.36588324652777776
186
187
/home/chirag/Downloads/GMRPD3/depth_u8/scene29/10.png /home/chirag/Downloads/GMRPD3/rgb/scene29/10.png
255
0.379892578125
187
188
/home/chirag/Downloads/GMRPD3/depth_u8/scene29/15.png /home/chirag/Downloads/GMRPD3/rgb/scene29/15.png
255
0.36092881944444444
188
189
/home/chirag/Downloads/GMRPD3/depth_u8/scene29/28.png /home/chirag/Downloads/GMRPD3/rgb/scene29/28.png
255
0.3621831597222222
189
190
/home/chirag/Downloads/GMRPD3/depth_u8/scene29/17.png /home/chirag/Downloads/GMRPD3/rgb/scene29/17.png
255
0.37216796875
190
191
/home/chirag/Downloads/GMRPD3/depth_u8/scene29/32.png /home/chirag/Downloads/GMRPD3/rgb/scene29/32.png
255
0.37244140625
191
192
/home/chirag/Downloads/GMRPD3/depth_u8/scene29/42.png /home/chirag/Downloads/GMRPD3/rgb/scene29/42.png
255
0.3776779513888889
192
193
/home/chirag/Downloads/GMRPD3/depth_u8/scene29/11.png /home/chirag/Downloads/GMRPD3/rgb/scene29/11.png
255
0.36597547743055553
193
194
/home/chirag/Downloads/GMRPD3/depth_u8/scene29

0.5061263020833333
248
249
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/102.png /home/chirag/Downloads/GMRPD3/rgb/scene22/102.png
255
0.5120421006944444
249
250
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/101.png /home/chirag/Downloads/GMRPD3/rgb/scene22/101.png
255
0.45206380208333335
250
251
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/65.png /home/chirag/Downloads/GMRPD3/rgb/scene22/65.png
255
0.5016720920138888
251
252
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/112.png /home/chirag/Downloads/GMRPD3/rgb/scene22/112.png
255
0.48245985243055556
252
253
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/47.png /home/chirag/Downloads/GMRPD3/rgb/scene22/47.png
255
0.538642578125
253
254
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/10.png /home/chirag/Downloads/GMRPD3/rgb/scene22/10.png
255
0.5286306423611111
254
255
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/105.png /home/chirag/Downloads/GMRPD3/rgb/scene22/105.png
255
0.46215169270833334
255
256
/home/chirag/Downloads/GMRPD

0.479697265625
310
311
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/40.png /home/chirag/Downloads/GMRPD3/rgb/scene22/40.png
255
0.5037684461805556
311
312
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/38.png /home/chirag/Downloads/GMRPD3/rgb/scene22/38.png
255
0.49428276909722224
312
313
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/74.png /home/chirag/Downloads/GMRPD3/rgb/scene22/74.png
255
0.5159678819444444
313
314
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/16.png /home/chirag/Downloads/GMRPD3/rgb/scene22/16.png
255
0.5291623263888889
314
315
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/31.png /home/chirag/Downloads/GMRPD3/rgb/scene22/31.png
255
0.501416015625
315
316
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/20.png /home/chirag/Downloads/GMRPD3/rgb/scene22/20.png
255
0.5296733940972222
316
317
/home/chirag/Downloads/GMRPD3/depth_u8/scene22/13.png /home/chirag/Downloads/GMRPD3/rgb/scene22/13.png
255
0.5024197048611111
317
318
/home/chirag/Downloads/GMRPD3/depth_u8/sce

0.5510405815972222
372
373
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/28.png /home/chirag/Downloads/GMRPD3/rgb/scene24/28.png
255
0.5424587673611111
373
374
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/75.png /home/chirag/Downloads/GMRPD3/rgb/scene24/75.png
255
0.5373285590277778
374
375
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/17.png /home/chirag/Downloads/GMRPD3/rgb/scene24/17.png
255
0.5411360677083333
375
376
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/32.png /home/chirag/Downloads/GMRPD3/rgb/scene24/32.png
255
0.5386371527777778
376
377
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/42.png /home/chirag/Downloads/GMRPD3/rgb/scene24/42.png
255
0.5250173611111111
377
378
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/85.png /home/chirag/Downloads/GMRPD3/rgb/scene24/85.png
255
0.5435026041666666
378
379
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/67.png /home/chirag/Downloads/GMRPD3/rgb/scene24/67.png
255
0.5477430555555556
379
380
/home/chirag/Downloads/GMRPD3/depth

0.5421484375
434
435
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/44.png /home/chirag/Downloads/GMRPD3/rgb/scene24/44.png
255
0.5297634548611111
435
436
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/59.png /home/chirag/Downloads/GMRPD3/rgb/scene24/59.png
255
0.5206684027777778
436
437
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/69.png /home/chirag/Downloads/GMRPD3/rgb/scene24/69.png
255
0.5225705295138889
437
438
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/50.png /home/chirag/Downloads/GMRPD3/rgb/scene24/50.png
255
0.5455967881944445
438
439
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/100.png /home/chirag/Downloads/GMRPD3/rgb/scene24/100.png
255
0.5125509982638888
439
440
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/63.png /home/chirag/Downloads/GMRPD3/rgb/scene24/63.png
255
0.5260774739583334
440
441
/home/chirag/Downloads/GMRPD3/depth_u8/scene24/90.png /home/chirag/Downloads/GMRPD3/rgb/scene24/90.png
255
0.5261089409722223
441
442
/home/chirag/Downloads/GMRPD3/depth_u8/

495
496
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/73.png /home/chirag/Downloads/GMRPD3/rgb/scene26/73.png
255
0.3980631510416667
496
497
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/104.png /home/chirag/Downloads/GMRPD3/rgb/scene26/104.png
255
0.4111197916666667
497
498
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/96.png /home/chirag/Downloads/GMRPD3/rgb/scene26/96.png
255
0.3243771701388889
498
499
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/70.png /home/chirag/Downloads/GMRPD3/rgb/scene26/70.png
255
0.3229633246527778
499
500
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/81.png /home/chirag/Downloads/GMRPD3/rgb/scene26/81.png
255
0.37970811631944446
500
501
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/1.png /home/chirag/Downloads/GMRPD3/rgb/scene26/1.png
255
0.5286089409722222
501
502
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/103.png /home/chirag/Downloads/GMRPD3/rgb/scene26/103.png
255
0.38933702256944447
502
503
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/66.

0.6737185329861111
557
558
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/79.png /home/chirag/Downloads/GMRPD3/rgb/scene26/79.png
255
0.3863302951388889
558
559
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/78.png /home/chirag/Downloads/GMRPD3/rgb/scene26/78.png
255
0.37397569444444445
559
560
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/114.png /home/chirag/Downloads/GMRPD3/rgb/scene26/114.png
255
0.2825922309027778
560
561
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/111.png /home/chirag/Downloads/GMRPD3/rgb/scene26/111.png
255
0.3312326388888889
561
562
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/77.png /home/chirag/Downloads/GMRPD3/rgb/scene26/77.png
255
0.3253005642361111
562
563
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/21.png /home/chirag/Downloads/GMRPD3/rgb/scene26/21.png
255
0.696181640625
563
564
/home/chirag/Downloads/GMRPD3/depth_u8/scene26/106.png /home/chirag/Downloads/GMRPD3/rgb/scene26/106.png
255
0.3687033420138889
564
565
/home/chirag/Downloads/GMRPD3/de

255
0.403681640625
619
620
/home/chirag/Downloads/GMRPD3/depth_u8/scene30/45.png /home/chirag/Downloads/GMRPD3/rgb/scene30/45.png
255
0.40087999131944446
620
621
/home/chirag/Downloads/GMRPD3/depth_u8/scene30/19.png /home/chirag/Downloads/GMRPD3/rgb/scene30/19.png
255
0.425166015625
621
622
/home/chirag/Downloads/GMRPD3/depth_u8/scene30/24.png /home/chirag/Downloads/GMRPD3/rgb/scene30/24.png
255
0.41423936631944447
622
623
/home/chirag/Downloads/GMRPD3/depth_u8/scene30/26.png /home/chirag/Downloads/GMRPD3/rgb/scene30/26.png
255
0.40602105034722225
623
624
/home/chirag/Downloads/GMRPD3/depth_u8/scene23/62.png /home/chirag/Downloads/GMRPD3/rgb/scene23/62.png
255
0.35033962673611113
624
625
/home/chirag/Downloads/GMRPD3/depth_u8/scene23/2.png /home/chirag/Downloads/GMRPD3/rgb/scene23/2.png
255
0.5418771701388889
625
626
/home/chirag/Downloads/GMRPD3/depth_u8/scene23/55.png /home/chirag/Downloads/GMRPD3/rgb/scene23/55.png
255
0.36536783854166666
626
627
/home/chirag/Downloads/GMRPD3/depth_

0.5253211805555555
681
682
/home/chirag/Downloads/GMRPD3/depth_u8/scene23/30.png /home/chirag/Downloads/GMRPD3/rgb/scene23/30.png
255
0.5045692274305555
682
683
/home/chirag/Downloads/GMRPD3/depth_u8/scene23/76.png /home/chirag/Downloads/GMRPD3/rgb/scene23/76.png
255
0.33939453125
683
684
/home/chirag/Downloads/GMRPD3/depth_u8/scene23/95.png /home/chirag/Downloads/GMRPD3/rgb/scene23/95.png
255
0.3263216145833333
684
685
/home/chirag/Downloads/GMRPD3/depth_u8/scene23/64.png /home/chirag/Downloads/GMRPD3/rgb/scene23/64.png
255
0.32259874131944444
685
686
/home/chirag/Downloads/GMRPD3/depth_u8/scene23/37.png /home/chirag/Downloads/GMRPD3/rgb/scene23/37.png
255
0.5364713541666667
686
687
/home/chirag/Downloads/GMRPD3/depth_u8/scene23/108.png /home/chirag/Downloads/GMRPD3/rgb/scene23/108.png
255
0.3452376302083333
687
688
/home/chirag/Downloads/GMRPD3/depth_u8/scene23/14.png /home/chirag/Downloads/GMRPD3/rgb/scene23/14.png
255
0.5261154513888889
688
689
/home/chirag/Downloads/GMRPD3/depth_u

0.5219856770833333
743
744
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/22.png /home/chirag/Downloads/GMRPD3/rgb/scene21/22.png
255
0.5165755208333334
744
745
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/109.png /home/chirag/Downloads/GMRPD3/rgb/scene21/109.png
255
0.41637044270833334
745
746
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/35.png /home/chirag/Downloads/GMRPD3/rgb/scene21/35.png
255
0.5199338107638889
746
747
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/56.png /home/chirag/Downloads/GMRPD3/rgb/scene21/56.png
255
0.44973958333333336
747
748
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/72.png /home/chirag/Downloads/GMRPD3/rgb/scene21/72.png
255
0.41611219618055556
748
749
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/8.png /home/chirag/Downloads/GMRPD3/rgb/scene21/8.png
255
0.5139019097222223
749
750
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/51.png /home/chirag/Downloads/GMRPD3/rgb/scene21/51.png
255
0.5045008680555556
750
751
/home/chirag/Downloads/GMRPD3/de

804
805
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/18.png /home/chirag/Downloads/GMRPD3/rgb/scene21/18.png
255
0.5096875
805
806
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/61.png /home/chirag/Downloads/GMRPD3/rgb/scene21/61.png
255
0.4375
806
807
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/57.png /home/chirag/Downloads/GMRPD3/rgb/scene21/57.png
255
0.33539279513888887
807
808
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/43.png /home/chirag/Downloads/GMRPD3/rgb/scene21/43.png
255
0.5006206597222222
808
809
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/87.png /home/chirag/Downloads/GMRPD3/rgb/scene21/87.png
255
0.4350119357638889
809
810
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/89.png /home/chirag/Downloads/GMRPD3/rgb/scene21/89.png
255
0.4531369357638889
810
811
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/80.png /home/chirag/Downloads/GMRPD3/rgb/scene21/80.png
255
0.43823350694444446
811
812
/home/chirag/Downloads/GMRPD3/depth_u8/scene21/7.png /home/chirag/Downloa

0.41563910590277775
866
867
/home/chirag/Downloads/GMRPD3/depth_u8/scene28/28.png /home/chirag/Downloads/GMRPD3/rgb/scene28/28.png
255
0.4186838107638889
867
868
/home/chirag/Downloads/GMRPD3/depth_u8/scene28/17.png /home/chirag/Downloads/GMRPD3/rgb/scene28/17.png
255
0.4095594618055556
868
869
/home/chirag/Downloads/GMRPD3/depth_u8/scene28/32.png /home/chirag/Downloads/GMRPD3/rgb/scene28/32.png
255
0.4347504340277778
869
870
/home/chirag/Downloads/GMRPD3/depth_u8/scene28/42.png /home/chirag/Downloads/GMRPD3/rgb/scene28/42.png
255
0.43806315104166665
870
871
/home/chirag/Downloads/GMRPD3/depth_u8/scene28/11.png /home/chirag/Downloads/GMRPD3/rgb/scene28/11.png
255
0.4161968315972222
871
872
/home/chirag/Downloads/GMRPD3/depth_u8/scene28/4.png /home/chirag/Downloads/GMRPD3/rgb/scene28/4.png
255
0.418212890625
872
873
/home/chirag/Downloads/GMRPD3/depth_u8/scene28/1.png /home/chirag/Downloads/GMRPD3/rgb/scene28/1.png
255
0.4557280815972222
873
874
/home/chirag/Downloads/GMRPD3/depth_u8/sc

In [36]:
import cv2 
image=cv2.imread("/home/chirag/Documents/OpenCV_vinay_sir/RGB/0.png")
d= cv2.imread("/home/chirag/Documents/OpenCV_vinay_sir/Depth/0.png",cv2.IMREAD_UNCHANGED)
# d = cv2.cvtColor(d, cv2.COLOR_BGR2GRAY)
print(d.shape)
d=d.reshape((image.shape[0], image.shape[1], 1))
# from PIL import Image
# image = Image.open("/home/chirag/Documents/OpenCV_vinay_sir/Labels/0.png") 
# image.load() 
x = np.zeros((image.shape[0], image.shape[1], 4))
print(x.shape)
x[:,:,:3]= image
print(x[:,:,:3].shape)
x[:,:,3:]=d
print(x[:,:,3:].shape)
cv2.imwrite("/home/chirag/Documents/OpenCV_vinay_sir/sample.png",x)






(720, 1280)
(720, 1280, 4)
(720, 1280, 3)
(720, 1280, 1)


True

In [34]:
i=cv2.imread("/home/chirag/Documents/OpenCV_vinay_sir/sample.png",cv2.IMREAD_UNCHANGED)
print(i.shape)
rgb= i[:,:,:3]
cv2.imwrite("/home/chirag/Documents/OpenCV_vinay_sir/sample2.png",rgb)


(720, 1280, 4)


True

In [46]:
i=cv2.imread("/home/chirag/Documents/OpenCV_vinay_sir/Labels1/90.png",cv2.IMREAD_UNCHANGED)
a, cnts = np.unique(i, return_counts=True)
a==0 

array([  0, 255], dtype=uint8)

In [50]:
import random
#Generate 5 random numbers between 10 and 30
randomlist = random.sample(range(0, 1122), 1122)


In [ ]:
for i in randomlist:
    
    